name: dartrentcar
description: A sample application
dependencies:
  http_server: ^0.9.2
  logging: '>=0.11.1 <0.12.0'
  logging_handlers: ">=0.8.0 <0.9.0"
  rpc: '>=0.5.0 <0.6.0'
  shelf: '>=0.6.0 <0.7.0'
  shelf_route: '>=0.13.4 <0.14.0'
  shelf_rpc: '>=0.0.3 <0.0.4'
  polymer: ">=0.15.1 <0.17.0"
  core_elements: '^0.6.1'
  paper_elements: '^0.6.2'
transformers:
- polymer:
    entry_points: web/index.html